/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fundamentals;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
   
    @Test public void testLinkedListZip(){
        LinkedList linkedListCombined=new LinkedList();
        LinkedList linkedList1=new LinkedList();
        LinkedList linkedList2=new LinkedList();

        linkedList1.insert(1);
        linkedListCombined.zipLists(linkedList1,linkedList2);
        assertEquals("{ 1 } -> Null", linkedListCombined.toString());

        linkedList2.insert(1);
        linkedListCombined.zipLists(linkedList1,linkedList2);
        assertEquals("{ 1 } -> { 1 } -> Null", linkedListCombined.toString());

        linkedList1.insert(2);
        linkedList2.insert(2);

        linkedList1.insert(3);
        linkedList2.insert(3);

        linkedList1.append(4);
        linkedList2.append(4);



        linkedListCombined.zipLists(linkedList1,linkedList2);
        assertEquals("{ 3 } -> { 2 } -> { 1 } -> { 1 } -> { 4 } -> { 3 } -> { 2 } -> { 1 } -> { 4 } -> Null",linkedListCombined.toString());

    }
}
