/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package stacksandqueues;

import org.junit.Test;
import org.junit.*;
import static org.junit.Assert.*;

public class AppTest {

    @Test public void PseudoQueueTest() {

        PseudoQueue pseudoQueue= new PseudoQueue();
        assertEquals(null, pseudoQueue.dequeue());

        assertEquals(20, pseudoQueue.enqueue(20));
        assertEquals(15, pseudoQueue.enqueue(15));
        assertEquals(10, pseudoQueue.enqueue(10));
        assertEquals(5, pseudoQueue.enqueue(5));

        assertEquals(20, pseudoQueue.dequeue());
        assertEquals(15, pseudoQueue.dequeue());
        assertEquals(10, pseudoQueue.dequeue());
        assertEquals(5, pseudoQueue.dequeue());

        assertEquals(null, pseudoQueue.dequeue());

    }
}
