/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package stacksandqueues;

import org.junit.Test;
import org.junit.*;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testStack() {
        Stack s = new Stack();
        s.push(5);
        assertFalse(s.isEmpty());
        s.push(10);
        s.push(15);
        s.pop();
        assertEquals(10,s.pop());
        s.pop();
        Exception exception = assertThrows(NullPointerException.class, () -> {
            s.pop();
            s.peek();
        });
        String expectedMessage = "Stack is Empty";
        String actualMessage = exception.getMessage();
        assertTrue(actualMessage.contains(expectedMessage));
        assertTrue(s.isEmpty());

    }
    @Test public void testQueue() {
        Queue q = new Queue();
        q.enqueue(5);
        assertFalse(q.isEmpty());
        q.enqueue(10);
        assertEquals(5,q.dequeue());

        Exception exception = assertThrows(NullPointerException.class, () -> {
            q.dequeue();
            q.peek();
        });
        String expectedMessage = "Queue is Empty";
        String actualMessage = exception.getMessage();
        assertTrue(actualMessage.contains(expectedMessage));
        assertTrue(q.isEmpty());

    }
}
